### ISSUE TITLE
Logo and text alignment in the footer section

### ISSUE THREAD

**Issue by yashsehgal** [EquiCode/EquiCode-Website#2]
There's a small issue we are having in the website's footer section. The logo of EquiCode and the year text is not perfectly aligned.

![image](https://user-images.githubusercontent.com/62352288/121027572-b474c100-c7c4-11eb-8c50-75abcc984a10.png)

We can solve this maybe by setting `align-items: center;` or something like this.
Also, I would love to work on this issue.

**Comment by KhushiSharma22** [comment]
Definitely :)
