### ISSUE TITLE
Use a JSON for events 

### ISSUE THREAD

**Issue by felixfaisal** [EquiCode/EquiCode-Website#3]
Currently, All the events are hardcoded into components which are further segregated into `Current` `Past` and `Next` events. Not only are these files redundant but also makes adding event data difficult. 

Solution :hand: 
- All the event details shall be put into a JSON file which will then be fetched by React for displaying 
- We can also filter these events using a function into `Current` `Past` and `Next` events without having three separate files for each. 
- This allows us to easily add/update/delete event details without changing much of code

**Comment by KhushiSharma22** [comment]
This makes sense to me! We can work on this.

**Comment by srivastavayushi** [comment]
Awesome you can work on this !
